name = "notion-blog"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "out"

[vars]
# Variables will be set in the Cloudflare Dashboard for security

[ai]
binding = "AI"
