name = "notion-blog"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
# Variables will be set in the Cloudflare Dashboard for security
